//go:build linux && amd64

package runner

import "golang.org/x/sys/unix"

func sandboxSeccompArchitecture() (sandboxSeccompSpec, error) {
	return sandboxSeccompSpec{
		auditArch: unix.AUDIT_ARCH_X86_64,
		// AUDIT_ARCH_X86_64 also identifies x32 calls. Reject that ABI instead
		// of permitting x32 variants to bypass the native syscall denylist.
		rejectedNumberMask:    0x40000000,
		ioctlNumber:           unix.SYS_IOCTL,
		deniedIoctls:          []uint32{unix.TIOCSTI},
		socketNumber:          unix.SYS_SOCKET,
		allowedSocketFamilies: []uint32{unix.AF_UNIX, unix.AF_INET, unix.AF_INET6},
		deniedSyscalls: []uint32{
			unix.SYS_PTRACE,
			unix.SYS_SYSLOG,
			unix.SYS_PIVOT_ROOT,
			unix.SYS_CHROOT,
			unix.SYS_ACCT,
			unix.SYS_MOUNT,
			unix.SYS_UMOUNT2,
			unix.SYS_SWAPON,
			unix.SYS_SWAPOFF,
			unix.SYS_REBOOT,
			unix.SYS_IOPL,
			unix.SYS_IOPERM,
			unix.SYS_CREATE_MODULE,
			unix.SYS_INIT_MODULE,
			unix.SYS_DELETE_MODULE,
			unix.SYS_GET_KERNEL_SYMS,
			unix.SYS_QUERY_MODULE,
			unix.SYS_QUOTACTL,
			unix.SYS_NFSSERVCTL,
			unix.SYS_TUXCALL,
			unix.SYS_SECURITY,
			unix.SYS_VSERVER,
			unix.SYS_KEXEC_LOAD,
			unix.SYS_ADD_KEY,
			unix.SYS_REQUEST_KEY,
			unix.SYS_KEYCTL,
			unix.SYS_UNSHARE,
			unix.SYS_PERF_EVENT_OPEN,
			unix.SYS_FANOTIFY_INIT,
			unix.SYS_FANOTIFY_MARK,
			unix.SYS_NAME_TO_HANDLE_AT,
			unix.SYS_OPEN_BY_HANDLE_AT,
			unix.SYS_SETNS,
			unix.SYS_PROCESS_VM_READV,
			unix.SYS_PROCESS_VM_WRITEV,
			unix.SYS_KCMP,
			unix.SYS_FINIT_MODULE,
			unix.SYS_KEXEC_FILE_LOAD,
			unix.SYS_BPF,
			unix.SYS_USERFAULTFD,
			unix.SYS_IO_URING_SETUP,
			unix.SYS_IO_URING_ENTER,
			unix.SYS_IO_URING_REGISTER,
			unix.SYS_OPEN_TREE,
			unix.SYS_MOVE_MOUNT,
			unix.SYS_FSOPEN,
			unix.SYS_FSCONFIG,
			unix.SYS_FSMOUNT,
			unix.SYS_FSPICK,
			unix.SYS_PIDFD_GETFD,
			unix.SYS_PROCESS_MADVISE,
			unix.SYS_MOUNT_SETATTR,
			unix.SYS_QUOTACTL_FD,
			unix.SYS_PROCESS_MRELEASE,
			unix.SYS_OPEN_TREE_ATTR,
		},
	}, nil
}
